[package]
name = "adventofcode2019-rs"
version = "0.1.0"
authors = ["starfys"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.0-alpha.2"
